# Para que serve este arquivo:
# Este workflow automatiza a publicação da documentação do seu TEMPLATE.
# Ele é acionado sempre que há um push para a branch `main`.

name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch principal do seu template

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    # Concede permissões de escrita para o job
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        # CORREÇÃO: Atualizado para a versão v4 da action
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5 # Também atualizado para a versão mais recente
        with:
          python-version: 3.11

      - name: Install documentation dependencies
        run: |
          pip install -r requirements-docs.txt

      - name: Deploy documentation to GitHub Pages
        run: mkdocs gh-deploy --force

